version: "3.8"

services:
  jobmanager:
    image: flink:1.18.1-scala_2.12-java17
    depends_on:
      mavenbuild:
        condition: service_completed_successfully
    ports:
      - "8081:8081"
    command: standalone-job --job-classname FlinkStreaming.DataStreamJob /opt/flink/usrlib/target/flink-streaming-1.0-SNAPSHOT.jar
    volumes:
      - ./target:/opt/flink/usrlib
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        parallelism.default: 2  

  taskmanager:
    image: flink:1.18.1-scala_2.12-java17
    depends_on:
      - jobmanager
    command: taskmanager
    volumes:
      - ./target:/opt/flink/usrlib
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 2
        parallelism.default: 2

  mavenbuild:
    image: maven:3.8.4-openjdk-17-slim
    command: mvn clean package
    volumes:
      - .:/opt/flink/project
    working_dir: /opt/flink/project