version: "3.8"

services:
  jobmanager:
    image: flink:1.18.1-java17
    container_name: jobmanager
    ports:
      - "8081:8081"
    environment:
      FLINK_PROPERTIES: "jobmanager.rpc.address: jobmanager"
    networks:
    - flink-network
    command: jobmanager

  taskmanager:
    image: flink:1.18.1-java17
    container_name: taskmanager
    environment:
      FLINK_PROPERTIES: "jobmanager.rpc.address: jobmanager"
    networks:
      - flink-network
    command: taskmanager

networks:
  flink-network:
    name: flink-network