FROM python:3.12-slim-bullseye

RUN apt-get update -y && apt-get install cron -y

WORKDIR /opt/python/scripts
COPY . /opt/python/scripts

ENV PATH="/usr/local/bin:${PATH}"

RUN echo "59 * * * * python /opt/python/scripts/real_time_data_retrieving.py >> /var/log/cron.log 2>&1" > /etc/cron.d/rt_cron
RUN chmod 0644 /etc/cron.d/rt_cron
RUN crontab /etc/cron.d/rt_cron
RUN touch /var/log/cron.log

# Run the command on container startup
CMD cron && tail -f /var/log/cron.log